[package]
name = "ezgl"
description = "Easy times with GL."
repository = "https://github.com/Lokathor/ezgl"
version = "0.1.0"
edition = "2021"

publish = false

[dev-dependencies]
beryllium = "0.11.2"

[dependencies]
#fermium = { version = "22604.0.0", features = ["static_bundled_build"] }
gl_constants = "0.1.1"
gl_struct_loader = "0.1.1"
gl_types = "0.1.0"
